### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by YaPaY** [upupming/Lenovo-Ideapad-500-14ISK-Clover#1]
Works Wifi and Webcam ?

**Comment by upupming** [comment]
> Works Wifi and Webcam ?

Intel WIFI card is not supported. Webcam not tested.

**Comment by YaPaY** [comment]
Thanks for info. I have Yoga 500 15isk and yesterday I installed Mojave first time. Now followings features doesn't work:
Keyboard
Touchpad
Webcam
Wifi

till today I was trying to first fix Wifi but now I am giving up. I think I need a laptop slot compatible broadcom BT chip. Do you have any suggestion.

Outer this, according to System Display my display adapter has got only 7MB. Is it normal. Is there any way to work Mobile Geforce 920 to work instead of Intel 5200 ?

**Comment by upupming** [comment]
@YaPaY 

1. WIFI: Intel WIFI is not supported, please buy another supported USB WIFI, there are a lot of wifi cards that don't need any drivers to work in Hackintosh, and you can reference to tonymacx86.
2. Graphics: Your configuration of Whatevergreen is not appropriate, please read my tutorial again.
