### ISSUE TITLE
Getting 4k 24fps 

### ISSUE THREAD

**Issue by YaPaY** [upupming/Lenovo-Ideapad-500-14ISK-Clover#2]
Hello,

first of all I thank you very much. I have a working hackintosh but one thing is not clear for me. I can get signal from HDMI to my 4k Samsung monitor but max resolution is 2560*1440.

According to Intel specs the Intel gfx card 520 can give 4k res with 24 fps from HDMI. 

How can I do that?

many thanks in advance

**Comment by upupming** [comment]
Sorry for the late reply. How much resolution can you get when you use Windows 10?

I have not tried any 4k resolution monitor, so there is no experience for me.
